---
## main variables for sharedhosting
##
## All values that are supposed to be at this level 

liverun: false


# section Firewall ports actions
sharedhostingfirewallports:
# which udp ports to open in 
  udpopeninports: '20,21,53,161,162'  
# which tcp ports to open in 
  tcpopeninports: '20,21,22,25,53,80,110,143,161,162,443,465,587,993,995,2077,2078,2082,2083,2086,2087,2095,2096,1243,3306'  
# which udp ports to open out 
  udpopenoutports: '20,21,53,113,123,873,2049,6277,24441'  
# which tcp ports to open out 
  tcpopenoutports: '20,21,22,25,37,43,53,80,110,113,443,587,873,2086,2087,2089,2703,993,143,1243,465,995,1493,4505,4506'  

# section Firewall white list for IP
sharedhostingfirewallwhiteip:

# section process list to ignore
sharedhostingcsfignorelist:
# 
  - { cmdignore: '/bin/sh /usr/bin/mysqld_safe', desc: 'commandline to ignore' }  
# 
  - { pcmdignore: '/home/.*/public_html/cgi-bin/script1\\.cgi', desc: 'perl regex commandline to ignore' }  
# 
  - { pcmdignore: '/usr/local/cpanel/3rdparty/bin/php /usr/local/cpanel/whostmgr/docroot/cgi/softaculous/cli\\.php\\.*', desc: 'perl regex commandline to ignore' }  

# section Active EasyApache profile
sharedhostingea:
# EasyApache Active profile 
  activeea: 'clap24ph5670ls'  

# section SNMP Configuration
sharedhostingserversnmp:
# server contact 
  server-contact-email: 'servers@brand1.com'  
# snmp monitor host 
  monitor-host: 'monitor.brand.com'  
# snmp community 
  monitor-community: 'public'  
# snmp read only user 
  read-only-user: 'rouser'  

# section pure-ftp local config
sharedhostingpureftpdlocal:
# pureftpd custom passvie port range 
  PassivePortRange: '30000 30999'  
