
---
# Validates that the path for whmapi output logs - (insert variable) exists
# Creates a file with the intended whmapi calls for role common 
# If the 'liverun' was supplied executes the calls in the created file and deletes it
- name: Include whmapi variables
  include_vars: whmapicommonvars.yaml
  tags:
    - always

- name: Make sure manage folder exists
  file: 
    path: "{{ whmapilogs }}"
    state: directory
  tags: whmapicommon,whmapi

- name: Create WHM api calls for common role
  template: 
    src: whmapicalls.txt.j2
    dest: "{{ whmapilogs }}/whmapicommoncalls.txt"
  tags: whmapicommon,whmapi

- name: Run the script
  script: "runwhmapi1.sh whmapicommoncalls.txt {{ whmapilogs }}"
  args:
    removes: "{{ whmapilogs }}/whmapicommoncalls.txt"
  tags: whmapicommon,whmapi
  when: liverun
