
---
# Validates that the path for whmapi output logs - (insert variable) exists
# Creates a file with the intended whmapi calls for role mailonly 
# If the 'liverun' was supplied executes the calls in the created file and deletes it
- name: Include whmapi variables
  include_vars: whmapimailonlyvars.yaml
  tags:
    - always

- name: Make sure manage folder exists
  file: 
    path: "{{ whmapilogs }}"
    state: directory
  tags: whmapimailonly,whmapi

- name: Create WHM api calls for mailonly role
  template: 
    src: whmapicalls.txt.j2
    dest: "{{ whmapilogs }}/whmapimailonlycalls.txt"
  tags: whmapimailonly,whmapi

- name: Run the script
  script: "runwhmapi1.sh whmapimailonlycalls.txt {{ whmapilogs }}"
  args:
    removes: "{{ whmapilogs }}/whmapimailonlycalls.txt"
  tags: whmapimailonly,whmapi
  when: liverun
