---
## main variables for common
##
## All values that are supposed to be at this level 

liverun: false


# section Firewall ports actions
commonfirewallports:
# which udp ports to open in 
  udpopeninports: '20,21,53,161,162'  
# which tcp ports to open in 
  tcpopeninports: '20,21,22,25,53,80,110,143,161,162,443,465,587,993,995,2077,2078,2082,2083,2086,2087,2095,2096,1243,3306'  
# which udp ports to open out 
  udpopenoutports: '20,21,53,113,123,873,2049,6277,24441'  
# which tcp ports to open out 
  tcpopenoutports: '20,21,22,25,37,43,53,80,110,113,443,587,873,2086,2087,2089,2703,993,143,1243,465,995,1493,4505,4506'  

# section Firewall white list for IP
commonfirewallwhiteip:
# 
  - { whiteip: '11.22.33.44', desc: 'Whitelist IP addresses' }  
# 
  - { whiteip: '11.22.33.45', desc: 'Whitelist IP addresses' }  
# 
  - { whiteip: '11.22.33.46', desc: 'Whitelist IP addresses' }  

# section process list to ignore
commoncsfignorelist:
# 
  - { cmdignore: '/bin/sh /usr/bin/mysqld_safe', desc: 'commandline to ignore' }  

# section Active EasyApache profile
commonea:

# section SNMP Configuration
commonserversnmp:
# server contact 
  server-contact-email: 'servers@brand1.com'  
# snmp monitor host 
  monitor-host: 'monitor.brand.com'  
# server timezone 
  timezone: 'UTC'  
# snmp community 
  monitor-community: 'public'  
# snmp read only user 
  read-only-user: 'rouser'  

# section pure-ftp local config
commonpureftpdlocal:
